logger:
  is_json: true
  add_source: false
  level: debug
  set_file: false
  file_name: logs/app.log
  max_size: 10
  max_backups: 3
  max_age: 7

client:
  timeout_req: 60 # second
  posts:
    url: http://posts:50051

httpserver:
  host: 127.0.0.1
  port: 50050
  enable_prefork: false
  enable_print_routes: true
  cors:
    allow_origins:
      - "*"
    allow_methods:
      - POST
      - GET
      - PUT
      - PATCH
      - DELETE
      - HEAD
      - OPTIONS
    allow_headers:
      - Origin
      - Content-Length
      - Content-Type
      - Accept
      - Authorization
    expose_headers:
      - Content-Length
    max_age: 3600
    allow_credentials: false
    allow_private_network: false