apiVersion: v1
kind: Service
metadata:
  name: posts
spec:
  type: ClusterIP
  selector:
    app: posts
  ports:
    - protocol: TCP # какой протокол использовать
      port: 50051 # внешний порт
      targetPort: 50051 # внутренний порт