logger:
  is_json: true
  add_source: false
  level: debug
  set_file: false
  file_name: logs/app.log
  max_size: 10
  max_backups: 3
  max_age: 7

postgres:
  host: postgres
  user: admin
  password: test
  dbname: test_db
  port: 5432
  sslmode: disable
  pool_max_conns: 10
  migrations_dir: file://migrations
  query_timeout: 2000000000 # 2 second

httpserver:
  host: 127.0.0.1
  port: 50051
  enable_prefork: false
  enable_print_routes: true
  cors:
    allow_origins:
      - "*"
    allow_methods:
      - POST
      - GET
      - PUT
      - PATCH
      - DELETE
      - HEAD
      - OPTIONS
    allow_headers:
      - Origin
      - Content-Length
      - Content-Type
      - Accept
      - Authorization
    expose_headers:
      - Content-Length
    max_age: 3600
    allow_credentials: false
    allow_private_network: false