volumes:
  postgres_volume:

services:
#  posts:
#    build: .
#    container_name: posts
#    restart: always
#    ports:
#      - '50051:50051'

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "54321:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data