apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: YWRtaW4= # Закодированное значение "admin" в base64
  POSTGRES_PASSWORD: dGVzdA== # Закодированное значение "test" в base64
  POSTGRES_DB: dGVzdF9kYg== # Закодированное значение "test_db" в base64